package com.example.visualcrawlerv05;

import android.annotation.SuppressLint;
import android.app.*;import android.content.*;import android.net.*;import android.os.*;import android.provider.MediaStore;import android.view.*;import android.webkit.*;import android.widget.*;
import org.json.*;import java.io.*;import java.nio.charset.StandardCharsets;import java.text.SimpleDateFormat;import java.util.*;

public class B extends Activity{
 WebView w;EditText url;TextView stat,out;ArrayList<String> links=new ArrayList<>(),blocks=new ArrayList<>();String bodySel="",listUrl="",last="";boolean run=false;int idx=0;Handler h=new Handler();
 @SuppressLint({"SetJavaScriptEnabled","AddJavascriptInterface"}) public void onCreate(Bundle b){super.onCreate(b);LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(10,10,10,10);
  LinearLayout top=new LinearLayout(this);top.setOrientation(LinearLayout.HORIZONTAL);url=new EditText(this);url.setSingleLine(true);url.setText("https://example.com");url.setLayoutParams(new LinearLayout.LayoutParams(0,-2,1));top.addView(url);top.addView(bt("이동",v->load()));top.addView(bt("?",v->help()));
  stat=new TextView(this);stat.setText("목록 페이지에서 [목록범위 선택]부터 시작해.");stat.setTextSize(13);stat.setPadding(6,6,6,6);
  HorizontalScrollView hs=new HorizontalScrollView(this);LinearLayout bar=new LinearLayout(this);bar.setOrientation(LinearLayout.HORIZONTAL);bar.addView(bt("목록범위 선택",v->selList()));bar.addView(bt("샘플글 열기",v->sample()));bar.addView(bt("본문영역 선택",v->selBody()));bar.addView(bt("전체수집 시작",v->start()));bar.addView(bt("다운로드 저장",v->save()));bar.addView(bt("초기화",v->reset()));hs.addView(bar);
  w=new WebView(this);w.setLayoutParams(new LinearLayout.LayoutParams(-1,0,1));WebSettings s=w.getSettings();s.setJavaScriptEnabled(true);s.setDomStorageEnabled(true);s.setLoadsImagesAutomatically(true);s.setMixedContentMode(WebSettings.MIXED_CONTENT_COMPATIBILITY_MODE);w.addJavascriptInterface(new Br(),"VC");w.setWebChromeClient(new WebChromeClient());w.setWebViewClient(new WebViewClient(){public void onPageFinished(WebView v,String u){url.setText(u);if(run)h.postDelayed(()->extract(),900);}});
  ScrollView sv=new ScrollView(this);sv.setLayoutParams(new LinearLayout.LayoutParams(-1,260));out=new TextView(this);out.setText("목록범위 선택 → 샘플글 열기 → 본문영역 선택 → 전체수집 시작 → 다운로드 저장");out.setTextSize(13);out.setPadding(8,8,8,8);sv.addView(out);
  r.addView(top);r.addView(stat);r.addView(hs);r.addView(w);r.addView(sv);setContentView(r);w.loadUrl(url.getText().toString());}
 Button bt(String t,View.OnClickListener l){Button b=new Button(this);b.setText(t);b.setOnClickListener(l);return b;}void st(String x){stat.setText(x);}void toast(String x){Toast.makeText(this,x,Toast.LENGTH_SHORT).show();}
 void load(){String x=url.getText().toString().trim();if(x.length()>0)w.loadUrl(x.startsWith("http")?x:"https://"+x);}
 void help(){new AlertDialog.Builder(this).setTitle("사용법").setMessage("1 목록 페이지에서 목록범위 선택\n2 글 목록 전체를 터치하면 링크를 기억함\n3 샘플글 열기 또는 직접 글 하나 접속\n4 본문영역 선택\n5 전체수집 시작\n6 다운로드 저장\n\n글 내부로 이동해도 처음 선택한 목록 링크는 계속 기억돼.").setPositiveButton("확인",null).show();}
 void selList(){if(run)return;w.evaluateJavascript(asset("list.js"),null);st("글 목록 전체를 감싸는 영역을 터치해.");}
 void selBody(){if(links.isEmpty()){toast("목록 먼저 선택");return;}w.evaluateJavascript(asset("body.js"),null);st("본문 영역을 터치해. 목록 "+links.size()+"개 기억 중.");}
 void sample(){if(links.isEmpty()){toast("목록 먼저 선택");return;}w.loadUrl(links.get(0));st("샘플글을 열었어. 목록은 계속 기억 중.");}
 void start(){if(links.isEmpty()){toast("목록 먼저 선택");return;}if(bodySel.isEmpty()){toast("본문 먼저 선택");return;}run=true;idx=0;blocks.clear();last="";out.setText("수집 시작...\n");w.loadUrl(links.get(0));}
 void extract(){String js="(function(){function c(t){return (t||'').replace(/\\u00a0/g,' ').replace(/[ \\t]+/g,' ').replace(/\\n{3,}/g,'\\n\\n').trim()}var e=null;try{e=document.querySelector("+JSONObject.quote(bodySel)+")}catch(x){}return JSON.stringify({title:c(document.title),url:location.href,text:e?c(e.innerText||e.textContent):'',ok:!!e})})();";w.evaluateJavascript(js,v->{try{JSONObject o=new JSONObject(dec(v));String text=o.optString("text").trim();if(text.isEmpty())text=o.optBoolean("ok")?"(텍스트 없음)":"(본문 영역을 찾지 못함)";blocks.add("제목: "+o.optString("title")+"\n주소: "+o.optString("url")+"\n\n"+text+"\n\n------------------------------\n");idx++;out.setText(join(false));st("수집 "+idx+" / "+links.size());if(idx<links.size())h.postDelayed(()->w.loadUrl(links.get(idx)),700);else{run=false;last=join(true);out.setText(last);st("수집 완료. 다운로드 저장을 눌러.");toast("완료");}}catch(Exception e){run=false;st("수집 오류: "+e.getMessage());}});}
 String dec(String v)throws Exception{return new JSONArray("["+v+"]").getString(0);}String join(boolean head){StringBuilder sb=new StringBuilder();if(head)sb.append("Visual Crawler v0.5 수집 결과\n목록 페이지: ").append(listUrl).append("\n수집 개수: ").append(blocks.size()).append("\n\n");for(String b:blocks)sb.append(b).append("\n");return sb.toString();}
 void save(){try{String c=last.isEmpty()?out.getText().toString():last;String name="visual_crawler_"+new SimpleDateFormat("yyyyMMdd_HHmmss",Locale.KOREA).format(new Date())+".txt";ContentValues v=new ContentValues();v.put(MediaStore.MediaColumns.DISPLAY_NAME,name);v.put(MediaStore.MediaColumns.MIME_TYPE,"text/plain");v.put(MediaStore.MediaColumns.RELATIVE_PATH,Environment.DIRECTORY_DOWNLOADS);Uri u=getContentResolver().insert(MediaStore.Downloads.EXTERNAL_CONTENT_URI,v);OutputStream os=getContentResolver().openOutputStream(u);os.write(c.getBytes(StandardCharsets.UTF_8));os.close();st("Downloads 저장 완료: "+name);toast("저장 완료");}catch(Exception e){st("저장 실패: "+e.getMessage());}}
 void reset(){run=false;links.clear();bodySel="";listUrl="";last="";blocks.clear();out.setText("초기화 완료.");st("목록범위 선택부터 시작해.");}
 String asset(String n){try{InputStream is=getAssets().open(n);ByteArrayOutputStream bo=new ByteArrayOutputStream();byte[] buf=new byte[4096];int k;while((k=is.read(buf))>0)bo.write(buf,0,k);return bo.toString("UTF-8");}catch(Exception e){return "VC.err('asset load fail')";}}
 public class Br{@JavascriptInterface public void list(String j){runOnUiThread(()->{try{JSONObject o=new JSONObject(j);JSONArray a=o.getJSONArray("links");LinkedHashSet<String> set=new LinkedHashSet<>();for(int i=0;i<a.length();i++){String x=a.optString(i);if(x.startsWith("http"))set.add(x);}links.clear();links.addAll(set);listUrl=o.optString("url",w.getUrl());out.setText("목록범위 선택 완료\n\n기억한 글 링크: "+links.size()+"개\n\n"+o.optString("preview")+"\n\n글 내부로 이동해도 목록은 유지돼.");st("목록 "+links.size()+"개 기억됨.");}catch(Exception e){st("목록 오류 "+e.getMessage());}});}@JavascriptInterface public void body(String s,String p){runOnUiThread(()->{bodySel=s;out.setText("본문영역 선택 완료\n\n"+p+"\n\n목록 "+links.size()+"개 기억 중.");st("본문영역 기억됨. 전체수집 가능.");});}@JavascriptInterface public void err(String m){runOnUiThread(()->st("오류: "+m));}}
 public void onBackPressed(){if(run){toast("수집 중");return;}if(w.canGoBack())w.goBack();else super.onBackPressed();}
}
